#required = ["k8s.io/code-generator"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]



[[constraint]]
   name = "k8s.io/client-go"
   version = "kubernetes-1.10.0"

[[constraint]]
   name = "k8s.io/apimachinery"
   version = "kubernetes-1.10.0"

[[constraint]]
   name = "github.com/jmoiron/sqlx"
   version = "sqlx-v1.1"


[[constraint]]
   name = "github.com/spf13/viper"
   version = "v1.1.0"

# Doesn't work until https://github.com/golang/dep/pull/1545 is merged.
#[[constraint]]
#   name = "k8s.io/code-generator"
#   version = "kubernetes-1.10.0"

[prune]
  go-tests = true
