/*
Autogenerated do not change
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/glorfischi/k8sdb/pkg/client/clientset/versioned/typed/k8sdb/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFischiV1alpha1 struct {
	*testing.Fake
}

func (c *FakeFischiV1alpha1) Databases(namespace string) v1alpha1.DatabaseInterface {
	return &FakeDatabases{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFischiV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
