/*
Autogenerated do not change
*/

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	fischiv1alpha1 "github.com/glorfischi/k8sdb/pkg/client/clientset/versioned/typed/k8sdb/v1alpha1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	FischiV1alpha1() fischiv1alpha1.FischiV1alpha1Interface
	// Deprecated: please explicitly pick a version if possible.
	Fischi() fischiv1alpha1.FischiV1alpha1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	fischiV1alpha1 *fischiv1alpha1.FischiV1alpha1Client
}

// FischiV1alpha1 retrieves the FischiV1alpha1Client
func (c *Clientset) FischiV1alpha1() fischiv1alpha1.FischiV1alpha1Interface {
	return c.fischiV1alpha1
}

// Deprecated: Fischi retrieves the default version of FischiClient.
// Please explicitly pick a version.
func (c *Clientset) Fischi() fischiv1alpha1.FischiV1alpha1Interface {
	return c.fischiV1alpha1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.fischiV1alpha1, err = fischiv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.fischiV1alpha1 = fischiv1alpha1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.fischiV1alpha1 = fischiv1alpha1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
